Filtering for graphic, fixes #60, #57
semanticarts/ontology-toolkit pull request #62
Opened 2021-03-18 14:47 UTC by sa-bpelakh

See README changes for what was added.

2021-04-28 20:19 UTC, uscholdm requested changes
A few questions inline.  Suggest adding 2 or 3 examples showing off the major features. Copy and edit much faster than figuring it out from scratch. It would take me a while to figure this out from scratch and get it working, .

2021-05-20 18:01 UTC, sa-bpelakh commented on README.md
> +                        the specified URIs will be shown in full detail. If
When working with data in input files (as opposed to in a triple store), onto_tool assumes one ontology per file. Once that ontology URI is determined, if it is either not present on the include list or is present on the exclude list, entities from that ontology will not be rendered in the diagram.

When working with data in the triple store, the same filtering logic will be applied to named graphs.

2021-05-20 18:03 UTC, sa-bpelakh commented on README.md
> +Filters (only one can be used):
--schema and --data are mutually exclusive - only one type of graph can be generated at a time.

2021-06-24 14:58 UTC, sa-bpelakh commented on README.md
> +  --include [INCLUDE [INCLUDE ...]]
It's not nesting, it's a list of includes.

2021-06-24 14:59 UTC, merged